config/routes.rb
SyphusBeta::Application.routes.draw do
  match 'api/v1/auth', to: "api#auth"
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/about',   to: "pages#about"
  match '/contact', to: "pages#contact"

  root to: 'pages#home'

end

app/models/user.rb
class User < ActiveRecord::Base
  before_save :create_remember_token
  before_save :downcase_email

  attr_accessible :name, :email, :password, :password_confirmation, :auth_token
  has_secure_password

  validates :name, presence: true, length: { maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  validates :password, length: { minimum: 6 }
  validates :password_confirmation, presence: true

  def set_token(auth_token)
    self.update_attribute("auth_token", auth_token)
  end

  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end

    def downcase_email
      self.email = email.downcase
    end
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  # API Keys
  HUNCH_APP_ID       = ENV['HUNCH_APP_ID']
  HUNCH_APP_SECRET   = ENV['HUNCH_APP_SECRET']

  def auth
    unless params[:auth_token_key].nil?
      auth_token = get_auth_token(params[:auth_token_key])
      @user = current_user
      @user.set_token(auth_token)
      sign_in(@user)
      puts @user.auth_token
      redirect_to @user
    end
  end

  private

  def get_auth_token( auth_token_key )
    url = "http://api.hunch.com/api/v1/get-auth-token/?app_id=#{HUNCH_APP_ID}&auth_token_key=#{auth_token_key}"
    auth_sig = get_auth_sig(url, HUNCH_APP_SECRET)
    begin
      response = RestClient.get "#{url}&auth_sig=#{auth_sig}"
    rescue
      redirect_to current_user
    end
    result = JSON.parse(response)
    result["auth_token"]
  end

  def enc(string)
    return string.gsub(/%20/,'+').gsub(/[+\/@]/,'+' => '%2B', '/' => '%2F', '@' => '%4O')
  end

  def get_auth_sig(url, app_secret)
    params = {}
    URI.parse(url).query.split('&').each do |part|
      if name = part.split('=')[0] and val = part.split('=')[1]
        params[name] = val
      else
        params[name] = ''
      end
    end

    canonical = ''
    params.sort.each do |key,val|
      canonical += key + '=' + enc(val.encode('utf-8')) + '&'
    end

    #this removes the trailing &
    canonical = canonical[0,canonical.size-1]

    string_to_sign = enc(canonical) + app_secret
    return Digest::SHA1.hexdigest(string_to_sign)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    email = params[:session][:email].downcase unless params[:session][:email].nil?
    user = User.find_by_email(email) unless email.nil?
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render "new"
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # API Keys
  ETSY_KEYSTRING     = ENV['ETSY_KEYSTRING']
  ETSY_SHARED_SECRET = ENV['ETSY_SHARED_SECRET']
  TOPIC_STR = "cat_art-design%2Ccat_autos%2Ccat_eat-drink%2Ccat_men-s-fashion%2Ccat_home-garden%2Ccat_sports-fitness" #%2C == ','

  before_filter :signed_in_user, only: [:edit, :update, :show]
  before_filter :correct_user,   only: [:edit, :update, :show]
  before_filter :is_admin?,      only: [:index]

  def index
    if params[:sort_by].nil? || params[:sort_by] == "ID"
      @users = User.all
    elsif params[:sort_by] == "Name"
      @users = User.all.sort_by{ |n| n.name }
    else
      @users = User.all.sort_by{ |n| n.email }
    end
  end

  def show

    if @user = User.find(params[:id])
      unless @user.auth_token.blank?
        @listings = fill_listings(@user)
      end
    else
      redirect_to root_path
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to Syphus Training"
      redirect_to 'http://hunch.com/authorize/v1/?app_id=3148074'
    else
      flash[@user.errors]
      render "new"
    end
  end

  def edit
    begin
      @user = User.find(params[:id])
    rescue
      redirect_to root_path
    end
  end

  def update
    begin
      @user = User.find(params[:id])
      if @user.update_attributes(params[:user])
        sign_in @user
        flash[:sucess] = "User updated."
        render "show"
      else
        render "edit"
      end
    rescue
      redirect_to root_path
    end
  end

  def destroy
    begin
      User.find(params[:id]).delete
      redirect_to users_path
    rescue
      redirect_to root_path
    end
  end

  private

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_path, notice: "Please sign in." unless signed_in?
    end
  end

  def correct_user
    begin
      @user = User.find(params[:id])
      redirect_to root_path unless (current_user?(@user) || @user.admin?)
    rescue
      redirect_to signin_path
    end
  end

  def is_admin?
    redirect_to root_path unless current_user && current_user.admin?
  end

  def fill_listings(user)
    recommendation = get_recommendations(user.auth_token)
    get_etsy_listings(recommendation)
  end

  def get_etsy_listings(recommendations)
    keywords = recommendations.sample["tags"].sample.to_s.gsub(" ", "+")
    url = "http://openapi.etsy.com/v2/listings/active?api_key=#{ENV['ETSY_KEYSTRING']}&keywords=#{keywords}&includes=MainImage&limit=24&category=Geekery"
    begin
      response = RestClient.get url
    rescue
      redirect_to current_user
    end
    result = JSON.parse(response)
    result["results"]
  end

  def get_recommendations(auth_token)
    url = "http://api.hunch.com/api/v1/get-recommendations/?auth_token=#{auth_token}&topic_ids=#{TOPIC_STR}&sites=hn&exclude_likes=1&limit=100"
    begin
      response = RestClient.get url
    rescue
      redirect_to current_user
    end
    result = JSON.parse(response)
    result["recommendations"]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def button_to_remove_fields(name, f)
    f.hidden_field(:_destroy) + button_to_function(name, "remove_fields(this)")
  end
  
  def button_to_add_fields(name, f, association)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
      render(association.to_s.singularize + "_fields", :f => builder)
    end
    button_to_function(name, "add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")")
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    cookies.permanent[:remember_token] = { value: user.remember_token,
                                           expires: 7.days.from_now.utc }
    current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= user_from_remember_token
  end

  def current_user?(user)
    user == current_user
  end

  def sign_out
    current_user = nil
    cookies.delete(:remember_token)
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    clear_return_to
  end

  def store_location
    session[:return_to] = request.fullpath
  end

  def is_authorized?
    redirect_to root_path unless (current_user && current_user.admin?)
  end

  private

    def clear_return_to
      session.delete(:return_to)
    end

    def user_from_remember_token
      remember_token = cookies[:remember_token]
      User.find_by_remember_token(remember_token) unless remember_token.nil?
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hsty! | A HackNY Project</title>
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="<%= root_path %>">Hsty</a>
        <div class="nav-collapse">
          <ul class="nav">
            <% if signed_in? %>
              <li><%= link_to "Profile", current_user %></li>
            <% end %>
            <% if current_user && current_user.admin? %>
              <li><%= link_to "Users", users_path %></li>
            <% end %>
            <li><%= link_to "Contact Us", contact_path %></li>
            <li><%= link_to "About us", about_path %></li>
            <% if signed_in? %>
              <li><%= link_to "Sign out", signout_path, method: :delete, confirm: "You sure?" %></li>
            <% else %>
              <li><%= link_to "Sign up", signup_path %></li>
              <li><%= link_to "Sign in", signin_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="span12"><%= yield %></div>
    </div>
  </div>
</body>
</html>

app/views/pages/about.html.haml
%h1 About Us
%br
.well
  %h3 What is Hsty!?

  %p Hesty! uses the power of Hunch to find your likes and dislikes then |
    searches Etsy's unique database to find you something that fits your likes. |

app/views/pages/contact.html.haml
%h1 Contact Us

%br
.well
  %h2 Have more questions?
  %p call us!

app/views/pages/home.html.haml
%h1 Welcome to Htsy
%br
.well
  .row
    .span12
      %h4.center This site was built at hackNY! Htsy uses the computing power of Hunch to find you unique items |
        that suit your taste on Etsy. |

  .row
    .span12
      .main-button.center
        - unless signed_in?
          %br
          = button_to("Sign up here", signup_path, class:"btn-inverse goto-syphus")

app/views/users/edit.html.haml
%h1= "Edit #{@user.name}"

%br

.well
  = simple_form_for(@user, html: { class: ""}) do |u|
    =u.input :name, label: "Name"
    =u.input :email, label: "Email Address"
    =u.input :password, placeholder: "Password", label: false
    =u.input :password_confirmation, placeholder: "Confirm password", label: false
    =u.button :submit, class: "btn-primary btn-large"

    %br
    %br
    .btn.btn-mini.btn-danger
      = link_to "Delete user", @user, method: :delete, confirm: "Are you sure? Deleting a user cannot be undone.", class:"btn-delete-link"

app/views/users/index.html.haml
%h1 User Index

.well
  =button_to "Create New User", new_user_path, class: "btn-large btn-inverse"

  %table.table.table-striped
    %thead
      %tr
        %th= link_to '#', users_path(sort_by:"ID")
        %th= link_to "Name", users_path(sort_by:"Name")
        %th= link_to "Email", users_path(sort_by:"Email")
        %th 
        %th 
        %th 

    %tbody
      -@users.each do |u|
        %tr
          %td= u.id
          -if u.admin?
            %td{style: "font-weight:bolder"}= u.name
          -else
            %td= u.name
          %td= u.email
          %td= link_to "Profile", u
          %td= link_to "Edit", edit_user_path(u)
          %td= link_to "Destroy", u, method: :delete, confirm: "You Sure?"

app/views/users/new.html.haml
%h1 Sign up

%br
.well
  =simple_form_for(@user) do |u|
    =u.input :name, placeholder: "Name", label: false
    =u.input :email, placeholder: "Email", label: false
    =u.input :password, placeholder: "Password", label: false
    =u.input :password_confirmation, placeholder: "Confirm password", label: false
    =u.button :submit, class: "btn-inverse btn-large"

app/views/users/show.html.haml
%h1= "#{@user.name}\'s Etsy Suggestions"

%p#notice= notice

-if @user.auth_token.blank?
  =button_to "Register Hunch", 'http://hunch.com/authorize/v1/?app_id=3148074'
  %br

-if @listings
  %br
  #container
    - @listings.each do |listing|
      .item= link_to image_tag(listing["MainImage"]["url_fullxfull"]), listing["url"], target: "_blank"